---
title: "raven_output"
output: html_document
date: "2026-06-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("raven_output.r")
calls <- read_csv("data/High_confidence_bobom.csv") 
calls_parsed<-parse_calls(calls)
view(calls_parsed)
#find correlation between power and distance to nests
sensor_data <- analyze_calls(calls_parsed,"BOBO")
#sensor_data %>% arrange(desc(totalPower))
correlation <-cor(sensor_data$sum_dist,sensor_data$avg_power, method = "pearson",  use = "complete.obs")
correlation
```


MALE:

```{r}
library(tidyverse)
source("raven_output.r")
calls <- read_csv("data/High_confidence_bobom.csv")
calls_parsed<-parse_calls(calls) %>% filter(confidence >= 0.75)
```

```{r}
calls_parsed %>% 
  group_by(sensor) %>%
  count() %>%
  arrange(desc(n))
```

```{r}
#find correlation between power and distance to nests
sensor_data <- analyze_calls(calls_parsed,"BOBO")
 

#find and return correlation
correlation <-cor(sensor_data$sum_dist,sensor_data$avg_power, method = "pearson",  use = "complete.obs")
correlation
```

Draw graph
```{r echo=FALSE,warning=FALSE}
library(ggrepel)
nest_locations2 <-read_csv("data/nest_locations.csv",
                          col_types= cols(lat=col_double(), lon=col_double())) %>%
                          mutate(type= case_when(Species_code=="SAVS" ~ "savs_nest",
                                                 Species_code=="BOBO" ~ "bobo_nest",
                                                 is.na(Species_code) ~ "unknown_nest"));

nests <- nest_locations2 %>% filter(Species_code %in% c("BOBO"), lon>-73.277) %>% 
  mutate(Nest_id=substring(Nest_id,4))

ggplot() +
  geom_point(data=sensor_data,mapping=aes(x=lon,y=lat,alpha=avg_power),size=30, color="orange")+
   geom_text(data=sensor_data,aes(x=lon,y=lat,label = sensor))+
  geom_point(data=nests, mapping=aes(x=lon, y=lat,color=Species_code))+
  guides(alpha=FALSE)+ 
   labs(title="Heat map of song activity of male bobolinks",
        subtitle="Darker orange= higher activity",
        color="Nest species",
        x="Longitude",
        y="Latitude")+
  theme(axis.text.x = element_text(angle = -90, vjust = 1, hjust=1))
  
```

FEMALE:


```{r}
library(tidyverse)
source("raven_output.r")
calls <- read_csv("data/High_confidence_bobom.csv")
calls_parsed<-parse_calls(calls) %>% filter(confidence >= 0.75)
```

```{r}
calls_parsed %>% 
  group_by(sensor) %>%
  count() %>%
  arrange(desc(n))
```

```{r}
#find correlation between power and distance to nests
sensor_data <- analyze_calls(calls_parsed,"BOBO")

#find and return correlation
correlation <-cor(sensor_data$sum_dist,sensor_data$avg_power, method = "pearson",  use = "complete.obs")
correlation
```

Draw graph
```{r echo=FALSE,warning=FALSE}
library(ggrepel)
nest_locations2 <-read_csv("data/nest_locations.csv",
                          col_types= cols(lat=col_double(), lon=col_double())) %>%
                          mutate(type= case_when(Species_code=="SAVS" ~ "savs_nest",
                                                 Species_code=="BOBO" ~ "bobo_nest",
                                                 is.na(Species_code) ~ "unknown_nest"));

nests <- nest_locations2 %>% filter(Species_code %in% c("BOBO"), lon>-73.277) %>% 
  mutate(Nest_id=substring(Nest_id,4))

ggplot() +
  geom_point(data=sensor_data,mapping=aes(x=lon,y=lat,alpha=avg_power),size=30, color="orange")+
   geom_text(data=sensor_data,aes(x=lon,y=lat,label = sensor))+
  geom_point(data=nests, mapping=aes(x=lon, y=lat,color=Species_code))+
  guides(alpha=FALSE)+ 
   labs(title="Heat map of call activity of male bobolinks",
        subtitle="Darker orange= higher activity",
        color="Nest species",
        x="Longitude",
        y="Latitude")+
  theme(axis.text.x = element_text(angle = -90, vjust = 1, hjust=1))
  
```

SAVS:


```{r}
library(tidyverse)
source("raven_output.r")
calls <- read_csv("data/High_confidence_savs.csv")
calls_parsed<-parse_calls(calls) %>% filter(confidence >= 0.75)
```

```{r}
calls_parsed %>% 
  group_by(sensor) %>%
  count() %>%
  arrange(desc(n))
```

```{r}
#find correlation between power and distance to nests
sensor_data <- analyze_calls(calls_parsed,"SAVS")

#find and return correlation
correlation <-cor(sensor_data$sum_dist,sensor_data$avg_power, method = "pearson",  use = "complete.obs")
correlation
```

Draw graph
```{r echo=FALSE,warning=FALSE}
library(ggrepel)
nest_locations2 <-read_csv("data/nest_locations.csv",
                          col_types= cols(lat=col_double(), lon=col_double())) %>%
                          mutate(type= case_when(Species_code=="SAVS" ~ "savs_nest",
                                                 Species_code=="BOBO" ~ "bobo_nest",
                                                 is.na(Species_code) ~ "unknown_nest"));

nests <- nest_locations2 %>% filter(Species_code %in% c("SAVS"), lon>-73.277) %>% 
  mutate(Nest_id=substring(Nest_id,4))

ggplot() +
  geom_point(data=sensor_data,mapping=aes(x=lon,y=lat,alpha=avg_power),size=30, color="orange")+
   geom_text(data=sensor_data,aes(x=lon,y=lat,label = sensor))+
  geom_point(data=nests, mapping=aes(x=lon, y=lat,color=Species_code))+
  guides(alpha=FALSE)+ 
   labs(title="Heat map of song activity of Savannah Sparrows",
        subtitle="Darker orange= higher activity",
        color="Nest species",
        x="Longitude",
        y="Latitude")+
  theme(axis.text.x = element_text(angle = -90, vjust = 1, hjust=1))
  
```